### ISSUE TITLE
Launching on simulator on El Capitan with Xcode 7 fails

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm-maven-plugin#29]
```
[ERROR] Failed to execute goal org.robovm:robovm-maven-plugin:1.6.0:ipad-sim (default) on project playn-hello-robovm: Failed to launch IOS Simulator: Unable to find a matching device [arch=x86_64, family=iPad, name=iPad-Retina, sdk=null] -> [Help 1]
```

Reproducable with latest PlayN and RoboVM 1.6.

**Comment by badlogic** [comment]
@samskivert looks like the PlayN Hello World sample is actually using RoboVM 1.0.0?

```
INFO] ------------------------------------------------------------------------
[INFO] Building PlayN Hello RoboVM 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/robovm/robovm-maven-plugin/1.0.0/robovm-maven-plugin-1.0.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/robovm/robovm-maven-plugin/1.0.0/robovm-maven-plugin-1.0.0.pom (5 KB at 9.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/robovm/robovm-maven-parent/1.0.0/robovm-maven-parent-1.0.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/robovm/robovm-maven-parent/1.0.0/robovm-maven-parent-1.0.0.pom (5 KB at 49.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/robovm/robovm-maven-plugin/1.0.0/robovm-maven-plugin-1.0.0.jar
Downloaded: https://repo.maven.apache.org/maven2/org/robovm/robovm-maven-plugin/1.0.0/robovm-maven-plugin-1.0.0.jar (23 KB at 166.0 KB/sec)
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ playn-hello-robovm ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ playn-hello-robovm ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/badlogic/workspaces/runtime-EclipseApplication/playn-samples/hello/robovm/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ playn-hello-robovm ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/badlogic/workspaces/runtime-EclipseApplication/playn-samples/hello/robovm/target/classes
[WARNING] bootstrap class path not set in conjunction with -source 1.7
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ playn-hello-robovm ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/badlogic/workspaces/runtime-EclipseApplication/playn-samples/hello/robovm/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ playn-hello-robovm ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ playn-hello-robovm ---
[INFO] No tests to run.
[INFO] 
[INFO] --- robovm-maven-plugin:1.0.0:ipad-sim (default) @ playn-hello-robovm ---
Downloading: https://repo.maven.apache.org/maven2/org/robovm/robovm-dist-compiler/1.0.0/robovm-dist-compiler-1.0.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/robovm/robovm-dist-compiler/1.0.0/robovm-dist-compiler-1.0.0.pom (4 KB at 40.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/robovm/robovm-dist-parent/1.0.0/robovm-dist-parent-1.0.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/robovm/robovm-dist-parent/1.0.0/robovm-dist-parent-1.0.0.pom (4 KB at 43.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/robovm/robovm-parent/1.0.0/robovm-parent-1.0.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/robovm/robovm-parent/1.0.0/robovm-parent-1.0.0.pom (6 KB at 58.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/robovm/robovm-dist-compiler/1.0.0/robovm-dist-compiler-1.0.0.jar
```

That won't work with El Capitan, Xcode 7 and iOS 9.0.

**Comment by badlogic** [comment]
Fixing up the `robovm.maven.version` to `1.6.1-SNAPSHOT` still produces the error.

**Comment by badlogic** [comment]
Running on an iphone-sim works as intended. Looks like only ipad targets are affected. Full stack trace:

```
ERROR] Failed to execute goal org.robovm:robovm-maven-plugin:1.6.1-SNAPSHOT:ipad-sim (default) on project playn-hello-robovm: Failed to launch IOS Simulator: Unable to find a matching device [arch=x86_64, family=iPad, name=null, sdk=null] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.robovm:robovm-maven-plugin:1.6.1-SNAPSHOT:ipad-sim (default) on project playn-hello-robovm: Failed to launch IOS Simulator
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to launch IOS Simulator
	at org.robovm.maven.plugin.AbstractIOSSimulatorMojo.execute(AbstractIOSSimulatorMojo.java:71)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.IllegalArgumentException: Unable to find a matching device [arch=x86_64, family=iPad, name=null, sdk=null]
	at org.robovm.compiler.target.ios.DeviceType.getBestDeviceType(DeviceType.java:230)
	at org.robovm.maven.plugin.AbstractIOSSimulatorMojo.execute(AbstractIOSSimulatorMojo.java:65)
	... 22 more
```

**Comment by badlogic** [comment]
@samskivert the default architecture for simulator builds has changed to x86_64. If you specify a simulator that only supports 32-bit without specifying the arch, things fail. Here's a snippet i used in `hello/robovm/pom.xml` to fix it:

```
<id>robosim</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.robovm</groupId>
            <artifactId>robovm-maven-plugin</artifactId>
            <version>1.6.1-SNAPSHOT</version>
            <configuration>
              <deviceName>iPad-Retina</deviceName>
              <arch>x86</arch>
...
```

Alternatively, you can use the iPad-Air device name instead of iPad-Retina, which supports x86_64.
